### ISSUE TITLE
Print leaderboard cuts off

### ISSUE THREAD

**Issue by conorm181** [conorm181/Deaffrey#25]
### Contact Details

conorm18@gmail.com

### What happened?

Leaderboard embed prints entries and then stops halfway through printing

### Version

V1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kahfree** [comment]
The embed message in discord has a character limit of something like 4096 or 6000 characters. Possible workaroud for this would be to have our regular leaderboard print in text, and then offer a new option like 'top10' or 'top5' so that we can still make use of the embed message.
I've thought about the idea of splitting the leaderboard into 'chunks' that get sent, almost like pagination. But because you can't send back an array of messages to one user send message, I don't see how someting like that would be possible.

**Comment by kahfree** [comment]
When the leaderboard starts to get cutoff in the server we can come back to this ticket. For now, the changes can be left unmade.
